#!/bin/sh

connection="$(iw dev wlan0 link)"

[ "$connection" = "Not connected." ] && echo "" && pkill -RTMIN+7 dwmblocks && exit

ipaddr=$(ip addr show wlan0 | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" | head -n1)
ssid="$(echo "$connection" | grep "SSID:" | cut -f 2 -d ' ')"
signal="$(echo "$connection" | grep "signal:" | cut -f 2 -d ' ')"
signal_strength="$(echo $signal | sed 's/\ *//; s/dBm//; s/-//')"
rx="$(expr $(echo "$connection" | grep "RX:" | cut -f 2 -d ' ') / 1024)"
tx="$(expr $(echo "$connection" | grep "TX:" | cut -f 2 -d ' ') / 1024)"

if [ "$signal_strength" -gt 80 ]; then
	signal_desc="Very poor"
	icon=""
elif [ "$signal_strength" -gt 67 ]; then
	signal_desc="Poor"
	icon=""
elif [ "$signal_strength" -gt 60 ]; then
	signal_desc="Mediocre"
	icon=""
elif [ "$signal_strength" -gt 50 ]; then
	signal_desc="Good"
	icon=""
elif [ "$signal_strength" -gt 40 ]; then
	signal_desc="Very good"
	icon=""
else
	signal_desc="Excellent"
	icon=""
fi

case $BUTTON in
	1) notify-send 	"Connected to: $ssid" "IP: $ipaddr\nSignal strength: $signal dBm ($signal_desc)\nReceived: $rx KiB\nTransmitted: $tx KiB" ;;
	2 | 3) setsid "$TERMINAL" -e sudo wifi-menu ;;
esac

echo "$icon"
