#!/bin/sh

connection="$(cat /sys/class/net/eth0/operstate)"
stats=/sys/class/net/eth0/statistics
[ "$connection" = "down" ] && echo "" && exit

ipaddr=$(ip addr show eth0 | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" | head -n1)
rx="$(echo "$(cat $stats/rx_bytes) / 1024" | bc)"
tx="$(echo "$(cat $stats/tx_bytes) / 1024" | bc)"
icon=""
case $BUTTON in
	1) notify-send 	"Connected" "IP: $ipaddr\nReceived: $rx KiB\nTransmitted: $tx KiB" ;;
esac

echo "$icon"
