#!/bin/sh

combined_capacity=0
battery_count=0

for battery in /sys/class/power_supply/BAT?; do
	capacity="$(cat "$battery/capacity")"
	combined_capacity="$(echo "$capacity + $combined_capacity" | bc)"
	battery_count="$(echo "$battery_count + 1" | bc)"
done

combined_capacity="$(echo "$combined_capacity / $battery_count" | bc)"

if [ "$combined_capacity" -lt "20" ]; then
	echo "⚠"
	notify-send "‼ Baterry low!" "🔋$combined_capacity% remaining!"
else
	echo "" && exit
fi
