#!/bin/sh

avail="$(echo "$(cat /proc/meminfo | grep "MemAvailable" | awk '{print $2}') / 1024" | bc )"
total="$(echo "$(cat /proc/meminfo | grep "MemTotal" | awk '{print $2}') / 1024" | bc)"
used="$(echo "$total - $avail" | bc)"
icon=""
echo "$icon $used/$total"
