#!/bin/sh

for battery in /sys/class/power_supply/BAT?; do
	case "$(cat $battery/status)" in
		"Full") status="" ;;
		"Charging") status="" ;;
		"Discharging") status="" ;;
		"Not charging") status="" ;;
		"Unknown") status="" ;;
	esac

	capacity="$(cat "$battery/capacity")"

	if [ "$status" = "" ]; then
		printf "%s %s " "$status" "$capacity"
	else	
		printf "%s  %s " "$status" "$capacity"
	fi
done 
